name: flutter_smt5
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  onboarding: 3.1.0
  unicons: any
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  google_sign_in: ^5.4.3
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.1.0
  date_time_picker: ^2.1.0
  google_sign_in_web_redirect: ^0.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

