// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF39GFaNutgk4Sc_Sgw59K7YY2N0tB_0',
    appId: '1:593777247171:web:a2509e2fb0b27f16bb3376',
    messagingSenderId: '593777247171',
    projectId: 'task-management-apps-eb119',
    authDomain: 'task-management-apps-eb119.firebaseapp.com',
    storageBucket: 'task-management-apps-eb119.appspot.com',
    measurementId: 'G-BWDZCCECCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeabldkDnuXoTjEUZ_TBy9WI9aDrKEWlc',
    appId: '1:593777247171:android:9a37bc9ba18742c0bb3376',
    messagingSenderId: '593777247171',
    projectId: 'task-management-apps-eb119',
    storageBucket: 'task-management-apps-eb119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACxTlGwB-aHEnBHRzOGNxkPnwRK31o5U',
    appId: '1:593777247171:ios:04cc0620bb7d896cbb3376',
    messagingSenderId: '593777247171',
    projectId: 'task-management-apps-eb119',
    storageBucket: 'task-management-apps-eb119.appspot.com',
    androidClientId: '593777247171-cpfpfkd9smmm84607f11660t2sb8501h.apps.googleusercontent.com',
    iosClientId: '593777247171-hg92jc8v6sdokfisqm55j06pd3osvbme.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmt5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACxTlGwB-aHEnBHRzOGNxkPnwRK31o5U',
    appId: '1:593777247171:ios:04cc0620bb7d896cbb3376',
    messagingSenderId: '593777247171',
    projectId: 'task-management-apps-eb119',
    storageBucket: 'task-management-apps-eb119.appspot.com',
    androidClientId: '593777247171-cpfpfkd9smmm84607f11660t2sb8501h.apps.googleusercontent.com',
    iosClientId: '593777247171-hg92jc8v6sdokfisqm55j06pd3osvbme.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmt5',
  );
}
